// AUTO-GENERATED FILE. DO NOT MODIFY.
//
// This class was automatically generated by Apollo GraphQL plugin from the GraphQL queries it found.
// It should not be modified by hand.
//
package com.pointwelve.revealed.graphql

import com.apollographql.apollo.api.Input
import com.apollographql.apollo.api.InputFieldMarshaller
import com.apollographql.apollo.api.Operation
import com.apollographql.apollo.api.OperationName
import com.apollographql.apollo.api.Query
import com.apollographql.apollo.api.Response
import com.apollographql.apollo.api.ResponseField
import com.apollographql.apollo.api.ResponseFieldMapper
import com.apollographql.apollo.api.ResponseFieldMarshaller
import com.apollographql.apollo.api.ResponseReader
import com.apollographql.apollo.api.internal.SimpleOperationResponseParser
import com.apollographql.apollo.internal.QueryDocumentMinifier
import com.apollographql.apollo.response.ScalarTypeAdapters
import com.apollographql.apollo.response.ScalarTypeAdapters.DEFAULT
import com.pointwelve.revealed.graphql.fragment.PostDetail
import java.io.IOException
import kotlin.Any
import kotlin.Array
import kotlin.Boolean
import kotlin.Int
import kotlin.String
import kotlin.Suppress
import kotlin.collections.List
import kotlin.collections.Map
import kotlin.jvm.Throws
import kotlin.jvm.Transient
import okio.BufferedSource

@Suppress("NAME_SHADOWING", "UNUSED_ANONYMOUS_PARAMETER", "LocalVariableName",
    "RemoveExplicitTypeArguments", "NestedLambdaShadowedImplicitParameter")
data class GetAllPostQuery(
  val first: Input<Int> = Input.absent(),
  val commentFirst: Input<String> = Input.absent()
) : Query<GetAllPostQuery.Data, GetAllPostQuery.Data, Operation.Variables> {
  @Transient
  private val variables: Operation.Variables = object : Operation.Variables() {
    override fun valueMap(): Map<String, Any?> = mutableMapOf<String, Any?>().apply {
      if (first.defined) this["first"] = this@GetAllPostQuery.first.value
      if (commentFirst.defined) this["commentFirst"] = this@GetAllPostQuery.commentFirst.value
    }

    override fun marshaller(): InputFieldMarshaller = InputFieldMarshaller { writer ->
      if (this@GetAllPostQuery.first.defined) {
        writer.writeInt("first", this@GetAllPostQuery.first.value)
      }
      if (this@GetAllPostQuery.commentFirst.defined) {
        writer.writeString("commentFirst", this@GetAllPostQuery.commentFirst.value)
      }
    }
  }

  override fun operationId(): String = OPERATION_ID
  override fun queryDocument(): String = QUERY_DOCUMENT
  override fun wrapData(data: Data?): Data? = data
  override fun variables(): Operation.Variables = variables
  override fun name(): OperationName = OPERATION_NAME
  override fun responseFieldMapper(): ResponseFieldMapper<Data> = ResponseFieldMapper {
    Data(it)
  }

  @Throws(IOException::class)
  override fun parse(source: BufferedSource, scalarTypeAdapters: ScalarTypeAdapters): Response<Data>
      = SimpleOperationResponseParser.parse(source, this, scalarTypeAdapters)

  @Throws(IOException::class)
  override fun parse(source: BufferedSource): Response<Data> = parse(source, DEFAULT)

  data class Edge(
    val __typename: String = "Post",
    val fragments: Fragments
  ) {
    fun marshaller(): ResponseFieldMarshaller = ResponseFieldMarshaller { writer ->
      writer.writeString(RESPONSE_FIELDS[0], this@Edge.__typename)
      this@Edge.fragments.marshaller().marshal(writer)
    }

    companion object {
      private val RESPONSE_FIELDS: Array<ResponseField> = arrayOf(
          ResponseField.forString("__typename", "__typename", null, false, null)
          )

      operator fun invoke(reader: ResponseReader): Edge = reader.run {
        val __typename = readString(RESPONSE_FIELDS[0])
        val fragments = Fragments(reader)
        Edge(
          __typename = __typename,
          fragments = fragments
        )
      }
    }

    data class Fragments(
      val postDetail: PostDetail
    ) {
      fun marshaller(): ResponseFieldMarshaller = ResponseFieldMarshaller { writer ->
        writer.writeFragment(this@Fragments.postDetail.marshaller())
      }

      companion object {
        private val RESPONSE_FIELDS: Array<ResponseField> = arrayOf(
            ResponseField.forFragment("__typename", "__typename", listOf(
              ResponseField.Condition.typeCondition(arrayOf("Post"))
            ))
            )

        operator fun invoke(reader: ResponseReader): Fragments = reader.run {
          val postDetail = readFragment<PostDetail>(RESPONSE_FIELDS[0]) { reader ->
            PostDetail(reader)
          }
          Fragments(
            postDetail = postDetail
          )
        }
      }
    }
  }

  data class PageInfo(
    val __typename: String = "PageInfo",
    val hasNextPage: Boolean,
    val endCursor: String?
  ) {
    fun marshaller(): ResponseFieldMarshaller = ResponseFieldMarshaller { writer ->
      writer.writeString(RESPONSE_FIELDS[0], this@PageInfo.__typename)
      writer.writeBoolean(RESPONSE_FIELDS[1], this@PageInfo.hasNextPage)
      writer.writeString(RESPONSE_FIELDS[2], this@PageInfo.endCursor)
    }

    companion object {
      private val RESPONSE_FIELDS: Array<ResponseField> = arrayOf(
          ResponseField.forString("__typename", "__typename", null, false, null),
          ResponseField.forBoolean("hasNextPage", "hasNextPage", null, false, null),
          ResponseField.forString("endCursor", "endCursor", null, true, null)
          )

      operator fun invoke(reader: ResponseReader): PageInfo = reader.run {
        val __typename = readString(RESPONSE_FIELDS[0])
        val hasNextPage = readBoolean(RESPONSE_FIELDS[1])
        val endCursor = readString(RESPONSE_FIELDS[2])
        PageInfo(
          __typename = __typename,
          hasNextPage = hasNextPage,
          endCursor = endCursor
        )
      }
    }
  }

  data class GetAllPosts(
    val __typename: String = "PostConnection",
    val edges: List<Edge>?,
    val pageInfo: PageInfo
  ) {
    fun marshaller(): ResponseFieldMarshaller = ResponseFieldMarshaller { writer ->
      writer.writeString(RESPONSE_FIELDS[0], this@GetAllPosts.__typename)
      writer.writeList(RESPONSE_FIELDS[1], this@GetAllPosts.edges) { value, listItemWriter ->
        value?.forEach { value ->
          listItemWriter.writeObject(value?.marshaller())}
      }
      writer.writeObject(RESPONSE_FIELDS[2], this@GetAllPosts.pageInfo.marshaller())
    }

    companion object {
      private val RESPONSE_FIELDS: Array<ResponseField> = arrayOf(
          ResponseField.forString("__typename", "__typename", null, false, null),
          ResponseField.forList("edges", "edges", null, true, null),
          ResponseField.forObject("pageInfo", "pageInfo", null, false, null)
          )

      operator fun invoke(reader: ResponseReader): GetAllPosts = reader.run {
        val __typename = readString(RESPONSE_FIELDS[0])
        val edges = readList<Edge>(RESPONSE_FIELDS[1]) { reader ->
          reader.readObject<Edge> { reader ->
            Edge(reader)
          }
        }
        val pageInfo = readObject<PageInfo>(RESPONSE_FIELDS[2]) { reader ->
          PageInfo(reader)
        }
        GetAllPosts(
          __typename = __typename,
          edges = edges,
          pageInfo = pageInfo
        )
      }
    }
  }

  data class Data(
    val getAllPosts: GetAllPosts
  ) : Operation.Data {
    override fun marshaller(): ResponseFieldMarshaller = ResponseFieldMarshaller { writer ->
      writer.writeObject(RESPONSE_FIELDS[0], this@Data.getAllPosts.marshaller())
    }

    companion object {
      private val RESPONSE_FIELDS: Array<ResponseField> = arrayOf(
          ResponseField.forObject("getAllPosts", "getAllPosts", mapOf<String, Any>(
            "first" to mapOf<String, Any>(
              "kind" to "Variable",
              "variableName" to "first"),
            "after" to mapOf<String, Any>(
              "kind" to "Variable",
              "variableName" to "commentFirst")), false, null)
          )

      operator fun invoke(reader: ResponseReader): Data = reader.run {
        val getAllPosts = readObject<GetAllPosts>(RESPONSE_FIELDS[0]) { reader ->
          GetAllPosts(reader)
        }
        Data(
          getAllPosts = getAllPosts
        )
      }
    }
  }

  companion object {
    const val OPERATION_ID: String =
        "380e761958397d2ce489e20686bc858d911d2bb5f052f5c39de60ba6e1ead07d"

    val QUERY_DOCUMENT: String = QueryDocumentMinifier.minify(
          """
          |query getAllPost(${'$'}first: Int, ${'$'}commentFirst: String) {
          |  getAllPosts(first: ${'$'}first, after: ${'$'}commentFirst) {
          |    __typename
          |    edges {
          |      __typename
          |      ...PostDetail
          |    }
          |    pageInfo {
          |      __typename
          |      hasNextPage
          |      endCursor
          |    }
          |  }
          |}
          |fragment PostDetail on Post {
          |  __typename
          |  author {
          |    __typename
          |    id
          |    username
          |  }
          |  tags {
          |    __typename
          |    name
          |  }
          |  topic {
          |    __typename
          |    name
          |  }
          |  id
          |  excerpt
          |  subject
          |  createdAt
          |  totalLikesCount
          |  totalCommentsCount
          |  postViewCount
          |  status
          |}
          """.trimMargin()
        )

    val OPERATION_NAME: OperationName = OperationName { "getAllPost" }
  }
}
