// AUTO-GENERATED FILE. DO NOT MODIFY.
//
// This class was automatically generated by Apollo GraphQL plugin from the GraphQL queries it found.
// It should not be modified by hand.
//
package com.pointwelve.revealed.graphql.type

import com.apollographql.apollo.api.InputFieldMarshaller
import com.apollographql.apollo.api.InputType
import kotlin.String
import kotlin.Suppress
import kotlin.collections.List

/**
 * Inputs
 */
@Suppress("NAME_SHADOWING", "UNUSED_ANONYMOUS_PARAMETER", "LocalVariableName",
    "RemoveExplicitTypeArguments", "NestedLambdaShadowedImplicitParameter")
data class PostInput(
  val subject: String,
  val content: String,
  val topicId: String,
  val tagIds: List<String>
) : InputType {
  override fun marshaller(): InputFieldMarshaller = InputFieldMarshaller { writer ->
    writer.writeString("subject", this@PostInput.subject)
    writer.writeString("content", this@PostInput.content)
    writer.writeString("topicId", this@PostInput.topicId)
    writer.writeList("tagIds") { listItemWriter ->
      this@PostInput.tagIds.forEach { value ->
        listItemWriter.writeString(value)
      }
    }
  }
}
