// AUTO-GENERATED FILE. DO NOT MODIFY.
//
// This class was automatically generated by Apollo GraphQL plugin from the GraphQL queries it found.
// It should not be modified by hand.
//
package com.pointwelve.revealed.graphql.type

import kotlin.String

enum class PostStatus(
  val rawValue: String
) {
  NEW("NEW"),

  APPROVED("APPROVED"),

  BLOCKED("BLOCKED"),

  DELETED("DELETED"),

  /**
   * Auto generated constant for unknown enum values
   */
  UNKNOWN__("UNKNOWN__");

  companion object {
    fun safeValueOf(rawValue: String): PostStatus = values().find { it.rawValue == rawValue } ?:
        UNKNOWN__
  }
}
